[database]
# port = 5520
port = 5020

[backend]
# port = 5500
port = 5010

[user_agent]
macos = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"
